name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  run_tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install ruff

      - name: Run tests with Pytest
        run: |
            pytest tests/

      - name: Run Lint with Ruff
        run: |
          ruff check mi-app/backend

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
            docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest mi-app/tarea_prueba/backend

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/backend:latest

  build_and_push_github_actions_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CD_TOKEN }}

      - name: Build Docker image for GitHub Actions
          run: |
            docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest mi-app/tarea_prueba/backend
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY}/backend:latest